name: Deploy to GitHub Pages

on:
  push:
    branches:
      - dev  # Este workflow se ejecutará cuando haya cambios en la rama dev.

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout dev branch
        uses: actions/checkout@v3
        with:
          ref: dev  # Asegúrate de que se está trabajando sobre la rama dev

      - name: Set up Git
        uses: actions/setup-git@v2
        with:
          user-name: 'your-username'  # Reemplaza con tu nombre de usuario de GitHub
          user-email: 'your-email@example.com'  # Reemplaza con tu correo de GitHub

      - name: Merge dev into main
        run: |
          git fetch origin main
          git checkout main
          git merge dev --no-ff --no-edit
          
      - name: Push changes to main
        run: |
          git push origin main  # Empuja los cambios a la rama main

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Cambia esto si tu sitio tiene una carpeta diferente donde se generan los archivos estáticos



